var score = 0;
var currentAnswer1 = Answerbag.first.question1.value;
var currentAnswer2 = Answerbag.first.question2.value;
var currentAnswer3 = Answerbag.first.question3.value;
var currentAnswer4 = Answerbag.first.question4.value;
var currentAnswer5 = Answerbag.first.question5.value;
var currentAnswer6 = Answerbag.first.question6.value;
var currentAnswer7 = Answerbag.first.question7.value;
var currentAnswer8 = Answerbag.first.question8.value;
var currentAnswer9 = Answerbag.first.question9.value;
var currentAnswer10 = Answerbag.first.question10.value;
var result= Answerbag.getElementById("text")
if (currentAnswer1=="substr()"){score+=10};
if (currentAnswer2=="document.myform.elements.length"){score+=10};
if (currentAnswer3==){score+=10};
if (currentAnswer4==){score+=10};
if (currentAnswer5==){score+=10};
if (currentAnswer6=="onmouseout"){score+=10};
if (currentAnswer7=="onmousescroller"){score+=10};
if (currentAnswer8=="Both A and B are true."){score+=10};
if (currentAnswer9=="charAt()"){score+=10};
if (currentAnswer10==){score+=10};